### ISSUE TITLE
Wrong classloader can be set in the current thread

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/global-events-addon#2]
See a topic on support forum: [link](https://www.cuba-platform.com/discuss/t/metaclass-not-found-for-class-in-globalevent-handler-method/9206)

CUBA version: 7.0.6
Addon version: 0.4

### Test case

1. Create a global event to fire
2. Create a service that will fire the event
3. Extend main window and subscribe for the event
4. Create any entity and open it in editor in event listener method
5. Create scheduled task that will trigger the service

#### Stacktrace

```Java
10:06:23.746 ERROR com.haulmont.cuba.web.log.AppLog        - Exception: 
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Can't find metaClass 'com.haulmont.cuba.security.entity.User'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_121]
	at com.vaadin.server.VaadinSession$FutureAccess.get(VaadinSession.java:102) ~[vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:2021) [vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1007) ~[vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1983) [vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1949) [vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1406) ~[vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	at com.haulmont.addon.globalevents.web.GlobalUiEvents.publish(GlobalUiEvents.java:67) ~[na:na]
	at com.haulmont.addon.globalevents.web.WebLocalClient.lambda$onMessage$0(WebLocalClient.java:84) ~[na:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.lang.IllegalStateException: Can't find metaClass 'com.haulmont.cuba.security.entity.User'
	at com.haulmont.cuba.gui.xml.data.DsContextLoader.loadMetaClass(DsContextLoader.java:354) ~[na:na]
	at com.haulmont.cuba.gui.xml.data.DsContextLoader.initDatasourceAttributes(DsContextLoader.java:240) ~[na:na]
	at com.haulmont.cuba.gui.xml.data.DsContextLoader.loadDatasource(DsContextLoader.java:220) ~[na:na]
	at com.haulmont.cuba.gui.xml.data.DsContextLoader.loadDatasources(DsContextLoader.java:94) ~[na:na]
	at com.haulmont.cuba.web.sys.WebScreens.loadDsContext(WebScreens.java:380) ~[na:na]
	at com.haulmont.cuba.web.sys.WebScreens.initDsContext(WebScreens.java:358) ~[na:na]
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:346) ~[na:na]
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:227) ~[na:na]
	at com.haulmont.cuba.web.sys.WebScreens.openEditor(WebScreens.java:1158) ~[na:na]
	at com.haulmont.cuba.gui.components.HasWindowManager.openEditor(HasWindowManager.java:82) ~[na:na]
	at com.company.sample.web.screens.ExtAppMainWindow.onAlarm(ExtAppMainWindow.java:25) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at com.haulmont.cuba.gui.events.sys.UiEventListenerMethodAdapter.doInvoke(UiEventListenerMethodAdapter.java:224) ~[na:na]
	at com.haulmont.cuba.gui.events.sys.UiEventListenerMethodAdapter.processEvent(UiEventListenerMethodAdapter.java:150) ~[na:na]
	at com.haulmont.cuba.gui.events.sys.UiEventListenerMethodAdapter.onApplicationEvent(UiEventListenerMethodAdapter.java:109) ~[na:na]
	at com.haulmont.cuba.gui.events.sys.UiEventsMulticasterImpl.invokeListener(UiEventsMulticasterImpl.java:73) ~[na:na]
	at com.haulmont.cuba.gui.events.sys.UiEventsMulticasterImpl.multicastEvent(UiEventsMulticasterImpl.java:66) ~[na:na]
	at com.haulmont.addon.globalevents.web.GlobalUiEvents.lambda$null$0(GlobalUiEvents.java:78) ~[na:na]
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1468) ~[vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	at com.haulmont.addon.globalevents.web.GlobalUiEvents.lambda$publish$1(GlobalUiEvents.java:77) ~[na:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_121]
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:2018) [vaadin-server-8.6.4-11-cuba.jar:8.6.4-11-cuba]
	... 11 common frames omitted
```

### Test project

[gl-ev-test.zip](https://github.com/cuba-platform/global-events-addon/files/3239931/gl-ev-test.zip)

**Comment by knstvk** [comment]
Fixed in 0.4.1
