### ISSUE TITLE
Nullpointer with open screen

### ISSUE THREAD

**Issue by DREIZ3R** [cuba-platform/global-events-addon#3]
I think this happens when I have a window open where @EventListener is registered but in the browser the main tab becomes different. Or when the browser is generally minimized or is under other windows.

Cuba-platform version: 7.0.9
Addon version: 0.4.1
```
17:36:00.132 ERROR com.haulmont.cuba.web.log.AppLog        - Exception: 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
	at com.vaadin.server.VaadinSession$FutureAccess.get(VaadinSession.java:102) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:2021) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1007) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1983) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1949) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1406) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
	at com.haulmont.addon.globalevents.web.GlobalUiEvents.publish(GlobalUiEvents.java:67) ~[cubaglevt-web-0.4.1.jar:na]
	at com.haulmont.addon.globalevents.web.WebLocalClient.lambda$onMessage$0(WebLocalClient.java:88) ~[cubaglevt-web-0.4.1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.NullPointerException: null
```

**Comment by MrHelp** [comment]
I think this happens when I have a window open where @EventListener is registered but in the browser the main tab becomes different. Or when the browser is generally minimized or is under other windows.
